behaviors:
  Snake:
    trainer_type: ppo #ppo #poca
    hyperparameters:
      batch_size: 128  #512 #128 #1024
      buffer_size: 1024 #5120 #1024 #10240
      learning_rate: 0.0003
      beta: 0.01 #0.03 #0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 8 #5 #3
      learning_rate_schedule: constant #linear #constant
    network_settings:
      normalize: false #false
      hidden_units: 512 #256 #512
      num_layers: 2 #3 #2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.5
        network_settings:
          hidden_units: 256
        learning_rate: 0.0003
    keep_checkpoints: 10
    max_steps: 20000000
    time_horizon: 128
    summary_freq: 5000
environment_parameters:
  target_vertical:
    curriculum:
        - name: Lesson0
          completion_criteria:
            measure: reward
            behavior: Snake
            signal_smoothing: true
            min_lesson_length: 1000
            threshold: 3 #0.4 #2
          value: 0.3
        - name: Lesson1
          completion_criteria:
            measure: reward
            behavior: Snake
            signal_smoothing: true
            min_lesson_length: 1000
            threshold: 3 #0.5 #2.5
          value: 0.5
        - name: Lesson2
          completion_criteria:
            measure: reward
            behavior: Snake
            signal_smoothing: true
            min_lesson_length: 1000
            threshold: 3 #0.7 #3.5
          value: 0.7
        - name: Lesson3
          value: 1
  target_horizontal:
      curriculum:
        - name: Lesson0
          completion_criteria:
            measure: reward
            behavior: Snake
            signal_smoothing: true
            min_lesson_length: 1000
            threshold: 3 #0.5 #2.5
          value: 0.3
        - name: Lesson1
          completion_criteria:
            measure: reward
            behavior: Snake
            signal_smoothing: true
            min_lesson_length: 1000
            threshold: 3 #0.6 #3
          value: 0.5
        - name: Lesson2
          completion_criteria:
            measure: reward
            behavior: Snake
            signal_smoothing: true
            min_lesson_length: 1000
            threshold: 3 #0.7 #3.5
          value: 0.75
        - name: Lesson3
          value: 1
  distance_punish:
      curriculum:
        - name: distance_punish_on
          completion_criteria:
            measure: reward
            behavior: Snake
            signal_smoothing: true
            min_lesson_length: 1000
            threshold: 2 #2  # Turn off penalty of increasing distance when the mean reward reach 2
          value: 1
        - name: distance_punish_off
          value: 0
  bend_punish:
      curriculum:
        - name: bend_punish_off
          completion_criteria:
            measure: reward
            behavior: Snake
            signal_smoothing: true
            min_lesson_length: 1000
            threshold: 3.5 #0.8 #4.2  # Turn on reward of less bending when the mean reward reach 2.5
          value: 0
        - name: bend_punish_on
          value: 0
  changing_evn:
      curriculum:
        - name: changing_evn
          completion_criteria:
            measure: reward
            behavior: Snake
            signal_smoothing: true
            min_lesson_length: 1000
            threshold: 3 #0.8 #4.2  # Turn on reward of less bending when the mean reward reach 2.5
          value: 1
        - name: fix_evn
          value: 1
  obstacle_active:
      curriculum:
        - name: obstacle_active_false
          completion_criteria:
            measure: reward
            behavior: Snake
            signal_smoothing: true
            min_lesson_length: 2000
            threshold: 3.5 #0.8 #4.2  # Turn on reward of less bending when the mean reward reach 2.5
          value: 0
        - name: obstacle_active_true
          value: 1